### ISSUE TITLE
Setup publicly hosted version

### ISSUE THREAD

**Issue by kelunik** [facebook/DelegatedRecoverySpecification#6] opened 2017-03-07 08:02 UTC
I think the `.html` file should be available online with the right content-type header for easy reading. GitHub's raw feature only serves it as `text/plain`. Maybe setup GitHub Pages?

**Example**

https://cdn.rawgit.com/facebookincubator/DelegatedRecovery/d147414e397a8c456ec512588e4e7361db84f913/draft-hill-delegated-recovery.html

**Comment by hillbrad** [comment] 2017-03-07 17:28
Duplicate of #1 

We will be adding better browsable documentation soon, but the Facebook open source organization on GitHub is not currently set up to use GitHub Pages.

The raw.txt version should be pretty usable and has all the same information, and you can always download and view the HTML version locally. Apologies for the inconvenience.

**Closed as completed by hillbrad** 2017-03-07 17:28 UTC
